name: BansheeRPG
title: BansheeRPG 

author: Ian Hunter

url: https://www.ianhunter.ie
baseurl: /BansheeRPG

description: An Open-source TTRPG

remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-them

collections:
  doc:
    output: true
    permalink: /:collection/:categories/:name

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

categories-order:
 - Homepage
 - Character Creation
 - Species
 - Generic Cultures
 - Career
 - Class
 - Combatant Subclass
 - The Battlefield
 - Items
