name: BansheeRPG
title: BansheeRPG 

author: Ian Hunter

url: https://www.ianhunter.ie
baseurl: /BansheeRPG

description: An Open-source TTRPG

collections:
  doc:
    output: true
    permalink: /:collection/:categories/:name

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

